title: Kanshi Protocol
email: rob.nice@protonmail.com
description: >- # this means to ignore newlines until "baseurl:"
  I'm exploring Cyber Security, AI, and different programming languages!
  I use Elixir and Python for my company's projects. I love Elixir so it's
  great that I get to use it for work. But I want to learn a more "low level"
  language.

  So, I'm using AI to help me learn about Cyber Security and how I can leverage
  my experience of mostly Backend Web Development to build tools to help detect
  and remediate vulnerabilities in an ever growing threat landscape.
baseurl: "" # the subpath of your site, e.g. /blog
url: "rnice01.github.com" # the base hostname & protocol for your site, e.g. http://example.com
github_username: rnice01

# Build settings
theme: minima
plugins:
  - jekyll-feed
timezone: America/New_York
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
